name: CI
on:
  push:
    branches:
    - master
    tags:
    - "v*"
  pull_request:

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.3
    - uses: coursier/setup-action@v1.2.0-M3
      with:
        jvm: 8
        apps: cs
    - run: |
        ./mill docs.generate --npm-install --yarn-run-build
        scripts/website0/versioned-docs.sh --update
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        WEBSITE_DIR: docs/website
        VERSIONED_DOCS_REPO: almond-sh/versioned-docs
    - run: |
        scripts/website0/versioned-docs.sh
        ./mill docs.generate --npm-install --yarn-run-build --relativize
        scripts/website0/push-website.sh
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        WEBSITE_DIR: docs/website
        REPO: almond-sh/almond
        VERSIONED_DOCS_REPO: almond-sh/versioned-docs
